"use client";
import { useState } from "react";
import { records } from "../../lib/case";
import { Icon } from "./Icon";
export function CaseRecords() {
  const [record, setRecord] = useState<number | null>(null);
  return <div className="records-layout">
                <section className="records-list"><div className="section-heading"><h2>Medical records</h2><span>3 files</span></div><p className="muted">A small, hand-authored example record set.</p>{records.map((item, index) => <button className={`record-card ${record === index ? "selected" : ""}`} key={item.id} onClick={() => setRecord(index)}><span className="file-icon"><Icon name="file" /></span><span><strong>{item.title}</strong><small>{item.date} · {item.kind}</small></span><span className="record-arrow">↗</span></button>)}<div className="record-footnote">Synthetic text documents for exploring the starter. Never upload real patient records to this demo.</div></section>
                <section className="summary-card">{record === null ? <><div className="summary-top"><span className="eyebrow">REVIEW SUMMARY</span><span className="subtle-badge">Example content</span></div><h2>A brief view of the record</h2><p className="summary-intro">Three documents trace a fictional left shoulder complaint from the first visit to follow-up.</p><div className="summary-section"><h3>Initial presentation</h3><p>The June 3 note describes shoulder discomfort after lifting at work, with difficulty reaching overhead. <button className="source-link" onClick={() => setRecord(0)}>1</button></p></div><div className="summary-section"><h3>Course documented</h3><p>The therapy and follow-up notes describe improving comfort, with some overhead symptoms remaining. <button className="source-link" onClick={() => setRecord(1)}>2</button> <button className="source-link" onClick={() => setRecord(2)}>3</button></p></div><div className="summary-section"><h3>Gaps to review</h3><p>These example records do not include imaging, standardized functional scores, or a final impairment determination.</p></div><div className="summary-footer"><span className="small-check">✓</span> Hand-authored summary · Click a source number to read its record</div></> : <><div className="summary-top"><button className="text-button" onClick={() => setRecord(null)}>← Back to summary</button><a className="text-button" href={records[record].file} download>Download .txt ↓</a></div><h2>{records[record].title}</h2><pre className="record-content">{records[record].text}</pre></>}</section>
              </div>;
}
