"use client";
import { type ReactElement } from "react";
import { RFA_LIFECYCLE_LABELS, type RfaListQuery, type RfaListResult } from "@mindbill/browser";
type Bucket = NonNullable<RfaListQuery["agingBucket"]>;
const buckets: { id: Bucket; label: string }[] = [{ id: "0_5", label: "0–5 days" }, { id: "6_14", label: "6–14 days" }, { id: "15_30", label: "15–30 days" }, { id: "31_plus", label: "31+ days" }];
const groups = [{ title: "Needs attention", tone: "attention", states: ["incomplete", "failed"] }, { title: "Awaiting decision", tone: "waiting", states: ["sent", "received"] }, { title: "Finished", tone: "finished", states: ["closed", "canceled"] }] as const;
export function RfaOverview({ summary, onSelect }: { summary: RfaListResult["summary"]; onSelect: (status: string, bucket?: Bucket) => void }): ReactElement {
  const aging = summary.aging;
  const countButton = (count: number, title: string, status: string, bucket?: Bucket) => count ? <button type="button" className="mbrfa-count" aria-label={`${title}: ${count} requests`} onClick={() => onSelect(status, bucket)}>{count.toLocaleString()}</button> : <span className="mbrfa-zero">0</span>;
  if (!summary.byLifecycleStatus) return <section className="mbrfa-overview" aria-label="Clinical review overview"><h3>Clinical review counts</h3><div className="mbrfa-legacy-grid">{Object.entries(summary.byStatus).map(([status, count]) => <button type="button" key={status} onClick={() => onSelect(status)}><span>{status.replaceAll("_", " ")}</span><strong>{count}</strong></button>)}</div></section>;
  return <div className="mbrfa-overview">
    <div className="mbrfa-overview-title"><div><h3>Status and aging</h3><p className="mbrfa-aging-basis">Calendar days since submission</p></div><span>{summary.total.toLocaleString()} total requests</span></div>
    {groups.map(group => <section className={`mbrfa-status-group mbrfa-${group.tone}`} key={group.title} aria-label={group.title}>
      <div className="mbrfa-aging-grid mbrfa-group-heading"><h4><i aria-hidden="true" />{group.title}</h4>{buckets.map(bucket => <span className="mbrfa-age-heading" key={bucket.id}>{bucket.label}</span>)}<span className="mbrfa-total-heading">Total</span></div>
      {group.states.map(status => <div className="mbrfa-aging-grid mbrfa-aging-row" key={status}>
        <strong>{RFA_LIFECYCLE_LABELS[status]}</strong>
        {buckets.map(bucket => <span className="mbrfa-age-cell" key={bucket.id}><span className="mbrfa-mobile-age">{bucket.label}</span>{group.tone === "waiting" && aging ? countButton(aging.byLifecycleStatus[status]?.[bucket.id] ?? 0, `${RFA_LIFECYCLE_LABELS[status]} · ${bucket.label} since submission`, status, bucket.id) : <span className="mbrfa-zero" aria-label="Not applicable">—</span>}</span>)}
        <span className="mbrfa-row-total">{countButton(summary.byLifecycleStatus?.[status] ?? 0, RFA_LIFECYCLE_LABELS[status], status)}</span>
      </div>)}
    </section>)}
    <p className="mbrfa-overview-footnote">Aging counts calendar days since submission, separately from the decision deadline. Only requests awaiting a treatment decision are aged.{!aging ? " Aging is unavailable from this server." : ""}</p>
    <button type="button" className="mbrfa-all-requests" onClick={() => onSelect("")}><strong>All requests</strong><span>{summary.total.toLocaleString()} <span aria-hidden="true">→</span></span></button>
  </div>;
}
export const rfaDashboardCss = `
.mbrfa-dashboard-heading{display:flex;justify-content:space-between;align-items:center;gap:16px;margin:18px 0}.mbrfa-update-note{color:var(--mb-muted);font-size:12px}.mbrfa-update-note:before{content:"";display:inline-block;width:6px;height:6px;margin-right:7px;border-radius:50%;background:var(--mb-accent)}
.mbtd .mbrfa-nav{display:flex;gap:24px;border-bottom:1px solid var(--mb-border);margin-bottom:22px;overflow-x:auto}.mbtd .mbrfa-nav button{flex-shrink:0;border:0;border-radius:0;background:transparent;white-space:nowrap;padding:12px 2px;color:var(--mb-muted);min-height:46px;border-bottom:2px solid transparent}.mbtd .mbrfa-nav button[aria-current=page]{color:var(--mb-accent);border-bottom-color:var(--mb-accent);font-weight:650}
.mbrfa-filters{display:flex;gap:14px;align-items:end;margin:18px 0 22px}.mbrfa-filters .mbrfa-search{flex:1}.mbrfa-filters label{min-width:0}.mbrfa-filters input{width:100%}.mbrfa-filters select{min-width:170px}.mbtd .mbrfa-clear{background:transparent;white-space:nowrap}.mbrfa-loading{padding:20px 0}
.mbrfa-overview-title{display:flex;justify-content:space-between;align-items:center;gap:16px;margin:0 0 14px}.mbrfa-overview h3{margin:0;font-size:16px}.mbtd .mbrfa-aging-basis{font-size:12px;color:var(--mb-muted);margin:4px 0 0}.mbrfa-overview-title>span{color:var(--mb-muted);font-size:13px}.mbrfa-status-group{border:1px solid var(--mb-border);border-radius:var(--mb-radius);background:var(--mb-surface);margin-bottom:16px;overflow:hidden}.mbrfa-aging-grid{display:grid;grid-template-columns:minmax(160px,1.7fr) repeat(4,minmax(65px,1fr)) minmax(65px,.8fr);align-items:center;gap:10px;padding:0 20px}.mbrfa-group-heading{padding:14px 20px;background:var(--mb-soft);border-bottom:1px solid var(--mb-border)}.mbrfa-group-heading h4{display:flex;align-items:center;gap:8px;font-size:14px;margin:0}.mbrfa-group-heading i{width:7px;height:7px;border-radius:50%;background:var(--mb-muted)}.mbrfa-attention h4 i{background:var(--mb-warning,#ad710d)}.mbrfa-waiting h4 i{background:var(--mb-accent)}.mbrfa-finished h4 i{background:var(--mb-success,#21805b)}.mbrfa-age-heading{background:color-mix(in srgb,var(--mb-accent) 8%,var(--mb-surface));border-radius:5px;padding:5px 2px;text-align:center;font-size:11px;font-weight:650;white-space:nowrap}.mbrfa-total-heading{text-align:center;font-size:11px;text-transform:uppercase;color:var(--mb-muted);letter-spacing:.04em}.mbrfa-aging-row{min-height:58px;border-top:1px solid var(--mb-border)}.mbrfa-aging-row:nth-child(2){border-top:0}.mbrfa-aging-row>strong{font-size:13px;font-weight:500}.mbrfa-age-cell,.mbrfa-row-total{text-align:center;font-variant-numeric:tabular-nums}.mbrfa-zero{color:var(--mb-muted);font-size:13px}.mbtd .mbrfa-count{border:0;min-width:44px;min-height:44px;padding:7px;background:transparent;font-weight:700;color:var(--mb-accent)}.mbtd .mbrfa-count:hover{background:var(--mb-soft);text-decoration:underline}.mbrfa-mobile-age{display:none}.mbtd .mbrfa-overview-footnote{font-size:12px;margin:0 0 16px;color:var(--mb-muted)}
.mbtd .mbrfa-all-requests{display:flex;justify-content:space-between;width:100%;padding:16px 20px;background:var(--mb-soft);border-color:var(--mb-border)}.mbrfa-all-requests>span{font-weight:700;color:var(--mb-accent)}.mbrfa-legacy-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-top:16px}.mbrfa-legacy-grid button{display:flex;justify-content:space-between;text-transform:capitalize;background:var(--mb-surface)}
.mbrfa-results-heading,.mbrfa-pagination{display:flex;align-items:center;justify-content:space-between;gap:16px}.mbrfa-results-heading>span,.mbrfa-pagination>span{color:var(--mb-muted);font-size:12px}.mbrfa-pagination{margin:14px 0}.mbrfa-pagination>div{display:flex;gap:10px}
@media(max-width:700px){.mbtd .mbrfa-nav{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));column-gap:12px;row-gap:0}.mbtd .mbrfa-nav button{text-align:left}.mbrfa-filters{flex-wrap:wrap}.mbrfa-filters .mbrfa-search{flex-basis:100%}.mbrfa-filters label:not(.mbrfa-search){flex:1}.mbrfa-dashboard-heading{align-items:center}.mbrfa-dashboard-heading button{max-width:66%;font-size:13px}.mbrfa-overview-title{align-items:baseline}.mbrfa-overview-title>span{font-size:11px}.mbrfa-aging-grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;padding:12px 14px}.mbrfa-group-heading{display:block}.mbrfa-age-heading,.mbrfa-total-heading{display:none}.mbrfa-aging-row>strong{grid-column:1/4;grid-row:1}.mbrfa-row-total{grid-column:4;grid-row:1;justify-self:end}.mbrfa-age-cell{grid-row:2;display:flex;flex-direction:column;align-items:center}.mbrfa-mobile-age{display:block;font-size:10px;color:var(--mb-muted)}.mbrfa-attention .mbrfa-age-cell,.mbrfa-finished .mbrfa-age-cell{display:none}.mbrfa-results-heading{align-items:start;flex-direction:column;gap:4px}}
`;
